### ISSUE TITLE
jamf binary path

### ISSUE THREAD

**Issue by anfalas** [rtrouton/CasperCheck#1]
From Casper Suite jss 9.8 Beta 2 Release Notes:

New Location for the jamf binary
The jamf binary is now located in /usr/local/jamf/bin/jamf. (The previous location was /usr/sbin/jamf.) The location is automatically updated during an upgrade to v9.8. Action is required if existing packages, scripts, or extension attributes reference the previous location of the jamf binary.
# 

The jamf-binary path used in caspercheck.sh ist still the one used in earlier Beta Versions (/usr/local/bin/jamf).

**Comment by rtrouton** [comment]
If you run `which jamf` with the new client, you'll get back a result of `/usr/local/bin/jamf`. That's a symlink pointing back to `/usr/local/jamf/bin/jamf`. While the actual `jamf` binary is located elsewhere in the filesystem, CasperCheck will be checking for the presence of the `/usr/local/bin/jamf` symlink. 

If the symlink is missing, CasperCheck's interpretation is that the symlink's absence means the Casper agent is broken and needs to be reinstalled.

**Comment by rtrouton** [comment]
I've added a note to the CasperCheck README to explain that CasperCheck will be checking for the presence of the `/usr/local/bin/jamf` symlink for Casper 9.8 and later on Macs running 10.7 and later.
