### ISSUE TITLE
CasperCheck error

### ISSUE THREAD

**Issue by MacBucky** [rtrouton/CasperCheck#3]
Unable to verify access to site network.  Exiting CasperCheck.

I doubled checked the variables and I simply cannot see what would cause this.  What line in the CasperCheck.sh file should I look at in order to determine what this might be tripping over.

Also, is this ONLY going to run AFTER a client has been logged into by a user?  I believe it should still run at the login window correct?

Thanks!

Mick

**Comment by rtrouton** [comment]
The relevant section for that error is the CheckSiteNetwork function:

[https://github.com/rtrouton/CasperCheck/blob/master/script/caspercheck.sh#L75-L101](https://github.com/rtrouton/CasperCheck/blob/master/script/caspercheck.sh#L75-L101)

That function gets called here in the script:

[https://github.com/rtrouton/CasperCheck/blob/master/script/caspercheck.sh#L393](https://github.com/rtrouton/CasperCheck/blob/master/script/caspercheck.sh#L393)

CasperCheck runs when the system starts up and will execute whether or not someone is logged in, so it will run fine on a Mac which is sitting at the loginwindow.
